@startuml
'https://plantuml.com/component-diagram

node "Articular-ES <<An Entity-Component-System Framework>>" {
    package "com.articular.core"
    package "com.articular.util"
}

package "com.articular.core" {
    [MemoryMap] <<interface>> #AD7FA8
    [SystemController] <<interface>> #FCAF3E
    [EntityComponentManager] <<manager>> #729FCF
    [CacheManager] <<manager>> #729FCF
    [EntityComponentManager] --(0 MemoryMap : requires
    [CacheManager] --(0 MemoryMap : requires
    [EntityComponentManager] --(0 SystemController : ===delegates

    node "Module" <<interface>> #8AE234 {
        [Component-A]
        [Component-B]
    }

    node "SystemControllers" #FCAF3E {
        [SystemsUpdater] <<controller>>
        [ComponentsUpdater] <<controller>>
        [SystemEntitiesUpdater] <<controller>>

        "SystemControllers" --|> [SystemController]
    }

    node "Dependencies" #BABDB6 {
        [ArticularSystem] <<interface>>
        [Component] <<component>> #8AE234
        [Entity] <<entity/id>> #8AE234

        [MemoryMap] ..> "Dependencies"
        [SystemController] --0 [ArticularSystem] : provides

        [Component] <|-- [Entity]
        [Component] <|-- [Module]
    }

    node "MemoryMaps" #AD7FA8 {
        [MemoryMap] <|-- "MemoryMaps"

        [SystemMap] <<memorymap>>
        [EntityComponentMap] <<memorymap>>
        [SystemComponentMap] <<memorymap>>
        [CacheMap] <<memorymap>>

        [EntityComponentMap] <-- [Module] : associates
    }
}

package "com.articular.util" {
    [Validator] <<utility>>
    [Validatable] <<interface>>
    [ArticularManager] <<manager>> #729FCF
    [ArticularManager] --|> [EntityComponentManager] : extends
    [ArticularManager] *--> [CacheManager] : composites
}

@enduml